### ISSUE TITLE
authy-python on Google App Engine:

### ISSUE THREAD

**Issue by fntintash** [authy/authy-python#10]
This bit of code in `authy/api/resources.py` doesn't work on GAE:

``` python
    def __default_headers(self):
        return {
            'User-Agent': "AuthyPython/{0} ({1}; Python {2})".format(
            __version__,
            platform.platform(True),
            platform.python_version()
        )}
```

On GAE, `platform.platform(True)` fails because it tries to open /usr/bin/python (or wherever the interpreter is located), and user code doesn't have access to that.

Replacing `platform.platform(True)` with something like `"google-app-engine"` works.

**Comment by aradhanasinha** [comment]
It still doesn't work. What is the purpose of this function?

**Comment by ndenny** [comment]
The submitted fix didn't actually use the platform_value it stores in the try-except block. I have a local fix, I can submit a PR if you'd like.

As stated in the bug, platform.platform(True) requires file access to the python executable, but that is not possible on GAE as it is sandboxed, so it throws an IOError.

**Comment by aradhanasinha** [comment]
I managed to get it to work with a the local fix mentioned by faried above, but I have no idea what the vargasx fix issue 10 actually accomplishes. In particular, I'm not sure why the function attempts to know the device it's being run on.

**Comment by AdrianaPineda** [comment]
@ndenny, @aradhanasinha sorry for the late response, we are catching up on the open issues and I saw you have a local fix. If you like to submit a PR I'll be more than happy to check it out and merge it. Thanks!

**Comment by ndenny** [comment]
Hi, I'm away for the office for a few days but I'll dig it out - ping me if you don't see it by the end of the week!

Nick Denny | VP Engineering & Co-founder | APImetrics
________________________________

**Comment by robinske** [comment]
Hi @ndenny closing this issue since #34 was merged. Let us know if there are any remaining issues.
