### ISSUE TITLE
Cannot use authy under python3

### ISSUE THREAD

**Issue by woodsonbruce** [authy/authy-python#16]
I was able to install authy for python3, but this call fails:

from authy.api import AuthyApiClient

Seems like it may not actually be ready for Python3

**Comment by woodsonbruce** [comment]
So, the version I got from using pip3 install authy was not Python3 savvy, but if I clone this repo and run setup.py install, I'm fine.  Problem solved.

**Comment by SableWalnut** [comment]
The latest changes in this repo haven't been published to PyPI, which probably needs to happen.

**Comment by vargasx** [comment]
@woodsonbruce @SableWalnut looks like it is now ` pip install authy==2.1.4`
