### ISSUE TITLE
What happened to the 2.1.4 release?

### ISSUE THREAD

**Issue by jayfk** [authy/authy-python#18]
PyPi shows `2.1.4` to be the latest release: https://pypi.python.org/pypi/authy

However, it doesn't seem like 2.1.4 is installable:

```
Collecting authy==2.1.4
  Could not find a version that satisfies the requirement authy==2.1.4 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 1.0.0, 2.0.0, 2.1.0, 2.1.1, 2.1.2, 2.1.3)
No matching distribution found for authy==2.1.4
```

**Comment by meshy** [comment]
It looks like the files have not been uploaded to pypi. Maintainers... any chance of re-pushing it?

**Comment by vargasx** [comment]
@jayfk @meshy looks like it is working now  `pip install authy==2.1.4`
