### ISSUE TITLE
Problem with Understanding API

### ISSUE THREAD

**Issue by anish-saha** [authy/authy-python#22]
Hi, I was wondering what the difference between verification_start (using via "sms") and request_sms was. I can't seem to find any ways to control the number of digits sent, and for the app that I am developing, I need a four-digit verification code (as is with the former command). However, I need to be able to resend codes. When I tested this, the codes became 7 digits long and I cannot figure out how options can be manipulated. Will this verification code also work with the command verification_check (such that if I use a combination of the two commands, the correct code will still update as necessary)? The documentation is a bit unclear so any help would be greatly appreciated. Thanks!

**Comment by robinske** [comment]
Hi @anish-saha sorry for the confusion! I just updated some of the docs in the README for more clarity. Can you email me at krobinson@twilio.com if you're still having a problem?
