### ISSUE TITLE
Add python3 classifier to setup.py to signal python3 support

### ISSUE THREAD

**Issue by jogo** [authy/authy-python#27]
https://github.com/authy/authy-python/blob/6f7aa284de2bcefc424b55ecdf04e128081837d3/setup.py#L26

When looking to check if a package supports python 3 a nice standard computer readable place to check is via classifiers.

https://github.com/brettcannon/caniusepython3

**Comment by jhasbani** [comment]
Yes, please! If python3 is known to work, it would be great for caniusepython3 to know it.
