### ISSUE TITLE
Problem verify SMS code

### ISSUE THREAD

**Issue by spolpen** [authy/authy-python#31]
Hi,

I'm trying to configure authy-python with my Twilio account. I follow the steps of both docs (Twilio and yours) and I can't get it working properly.

I receive the SMS and create the user in Authy users fine, but the SMS Code verify returns the following error all the times:

"No pending verifications for +34 NN-NNN-NNNN found."

The phone it's right but the verify doesn't works. 

How can I should fix this? I'm trying a lot of configurations but although I receiving SMS i can't verify it. 

Thanks and regards

**Comment by robinske** [comment]
Hi @spolpen sorry for the confusion! I just updated some of the docs in the https://github.com/authy/authy-python/blob/master/README.md for more clarity. Can you email me at krobinson@twilio.com if you're still having a problem?

**Comment by alexandriainfantino** [comment]
Hi @robinske 

I was wondering what the outcome of this issue was. We're running into a similar issue where a user requests a token, receives it within seconds, and inputs it for verification only to receive "No pending verifications for <phone number> found." 

When they request a new token they receive the same one and still get the "No pending verifications for <phone number> found." response when they input it for verification again.

**Comment by aureliendebord** [comment]
Hi @robinske,

I got the same problem as @alexandriainfantino `'error_code': '60023'`

**Comment by adebiaan** [comment]
Hi @robinske,

I'm also running into the same issue where stars the verification process and is unable to verify their code. They're using a US phone number (from Puerto Rico to be exact +1-787-...) and receiving the error message 

```"message"=>"No pending verifications for +1 787-... found."```

**Comment by SeverinDK** [comment]
Anything on this issue? I am experiencing the same problem.

**Comment by muhammadssr** [comment]
We are experiencing the same issue in my company. Any update on this?

**Comment by robinske** [comment]
Hey everyone, sorry this is happening! Any information you can share may help me track down a specific problem.
* country codes where this is happening?
* does this happen for all phone numbers, or just some?

I'll post more details here if I hear of any known issues.

1) For anyone happening on this from Google, this error is for Verify V1, if you're just getting started I'd recommend using Verify V2 (and upgrading if that's an option for you): 
https://www.twilio.com/docs/verify/api
https://www.twilio.com/docs/verify/migrating-1x-2x

2) This may mean that the verification has expired, verifications are valid for 10 minutes. This isn't the problem for @alexandriainfantino or @adebiaan (if you send the code again and get the same one, then the verification hasn't expired yet) but mentioning it in case that's true for some.

3) Doesn't sound like this is specific to the Python library - @adebiaan mentioned Ruby, so if you're still having issues it's best to *email support@twilio.com with details about your account/problem and we'll get you sorted there*. If you don't get an answer from support feel free to email me with additional information and I'll try my best to escalate it.

FYI @SeverinDK @muhammadssr

**Comment by sb5518** [comment]
Same issue here. I receive the message but authentication fails with the following error " Same issue here. I receive the message but authentication fails with the following error " No pending verifications for +54(911) XXXX-XXXX found"

**Comment by LeandroBarone** [comment]
> Same issue here. I receive the message but authentication fails with the following error " Same issue here. I receive the message but authentication fails with the following error " No pending verifications for +54(911) XXXX-XXXX found"

Just had exactly the same problem. Could bypass it by removing the "9" from the city dial code. This is not the correct behavior and should be fixed. "9" is our dial code for cellphones.
